import { Box, Container, Typography, Link, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper } from '@mui/material';

const TermsOfService = () => {
  return (
    <Box sx={{ bgcolor: '#ffffff', minHeight: '100vh', color: '#222', py: 20 }}>
      <Container maxWidth="lg">
        <Typography variant="h2" component="h1" sx={{ mb: 2, fontWeight: 700, fontSize: { xs: '2rem', md: '2.5rem' } }}>
          Terms of Service for BizNavigate
        </Typography>

        <Typography variant="body2" sx={{ mb: 1, color: '#666', fontSize: '0.875rem' }}>
          <strong>Last Updated:</strong> December 10, 2025
        </Typography>
        <Typography variant="body2" sx={{ mb: 6, color: '#666', fontSize: '0.875rem' }}>
          <strong>Effective Date:</strong> December 10, 2025
        </Typography>

        {/* 1. Introduction and Acceptance */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            1. Introduction and Acceptance
          </Typography>
          <Typography variant="body1" sx={{ mb: 2, color: '#666', lineHeight: 1.8 }}>
            These Terms of Service ("Terms," "Agreement") constitute a legally binding agreement between BIZNAVIGATE TECHNOLOGIES PRIVATE LIMITED ("BizNavigate," "we," "us," or "our") and you ("User," "Client," or "you"), governing your access to and use of the BizNavigate platform.
          </Typography>

          <Box sx={{ bgcolor: '#f0f7ff', p: 3, borderRadius: 2, mb: 3 }}>
            <Typography variant="h6" sx={{ mb: 2, fontWeight: 600, color: '#222' }}>Company Details:</Typography>
            <Box component="ul" sx={{ color: '#666', pl: 0, mb: 0, listStyle: 'none' }}>
              <li><Typography variant="body1" sx={{ mb: 1 }}><strong>Name:</strong> BIZNAVIGATE TECHNOLOGIES PRIVATE LIMITED</Typography></li>
              <li><Typography variant="body1" sx={{ mb: 1 }}><strong>Registered Address:</strong> C/O ERAMU P V, PALLIKKAL, VALIYAPUTHOOR HOUSE, TIRURANGADI, PUTHUR-PALLIKKAL, MALAPPURAM - 673636, KERALA, INDIA</Typography></li>
              <li><Typography variant="body1" sx={{ mb: 1 }}><strong>Email:</strong> <Link href="mailto:support@biznavigate.in" color="primary">support@biznavigate.in</Link></Typography></li>
              <li><Typography variant="body1" sx={{ mb: 1 }}><strong>Website:</strong> <Link href="https://www.biznavigate.in" color="primary">www.biznavigate.in</Link></Typography></li>
            </Box>
          </Box>

          <Typography variant="body1" sx={{ mb: 2, color: '#666', lineHeight: 1.8 }}>
            This Agreement is an electronic record under the Information Technology Act, 2000 and rules thereunder, as applicable and amended from time to time. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </Typography>
          <Typography variant="body1" sx={{ mb: 2, color: '#666', lineHeight: 1.8 }}>
            By accessing, browsing, or using the BizNavigate platform, you acknowledge that you have read, understood, and agree to be bound by these Terms. If you do not agree to these Terms, you must immediately cease using our Services.
          </Typography>
        </Box>

        {/* 2. Definitions */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            2. Definitions
          </Typography>
          <Typography variant="body1" sx={{ mb: 2, color: '#666', lineHeight: 1.8 }}>
            For the purposes of this Agreement, the following terms shall have the meanings set forth below:
          </Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 2 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}><strong>"Applicable Law"</strong> means all applicable Indian laws, statutes, rules, regulations, ordinances, and other pronouncements having the effect of law in India</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}><strong>"Applicable Data Protection Law"</strong> means the Digital Personal Data Protection Act, 2023 (DPDPA) and Information Technology Act, 2000</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}><strong>"Client Data"</strong> means all data, information, and content that you or your end users provide, upload, or transmit through the Services</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}><strong>"Platform"</strong> or <strong>"Services"</strong> means the BizNavigate software-as-a-service platform, including all features, functionalities, APIs, integrations, and related services</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}><strong>"SaaS"</strong> means Software-as-a-Service, the cloud-based software delivery model through which the Services are provided</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}><strong>"Subscription Period"</strong> means the period for which you have subscribed to the Services</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}><strong>"Third-Party Services"</strong> means services provided by third parties that integrate with or are accessible through the Platform, including Instagram, WhatsApp Business API, and Facebook</Typography></li>
          </Box>
        </Box>

        {/* 3. Scope of Services */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            3. Scope of Services
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>3.1 Service Description</Typography>
          <Typography variant="body1" sx={{ mb: 2, color: '#666', lineHeight: 1.8 }}>
            BizNavigate provides a cloud-based business automation and customer engagement platform that enables you to:
          </Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 3 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Integrate and manage Instagram Business accounts</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Integrate and manage WhatsApp Business accounts</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Automate customer communications and responses</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Manage customer inquiries, comments, and direct messages</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Analyze customer engagement and behavior</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Generate business reports and insights</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Manage marketing campaigns and notifications</Typography></li>
          </Box>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>3.2 Service Availability</Typography>
          <Typography variant="body1" sx={{ mb: 2, color: '#666', lineHeight: 1.8 }}>
            We strive to provide continuous availability of the Services. However, we do not guarantee uninterrupted or error-free operation. <strong>Service Level Commitment:</strong> We aim to maintain 99% uptime annually, calculated monthly, excluding scheduled maintenance and force majeure events.
          </Typography>
        </Box>

        {/* 4. License Grant and Restrictions */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            4. License Grant and Restrictions
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>4.1 License Grant</Typography>
          <Typography variant="body1" sx={{ mb: 3, color: '#666', lineHeight: 1.8 }}>
            Subject to your compliance with these Terms and payment of applicable fees, we grant you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Services during the Subscription Period solely for your internal business purposes.
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>4.2 License Restrictions</Typography>
          <Typography variant="body1" sx={{ mb: 1, color: '#666', lineHeight: 1.8 }}>You agree NOT to:</Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 2 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Reverse engineer, decompile, disassemble, or attempt to derive source code from the Services</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Use any robot, spider, scraper, or automated means to access the Services</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Use the Services for any illegal, fraudulent, or unauthorized purpose</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Violate any applicable laws, including data protection, privacy, and anti-spam regulations</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Resell, sublicense, rent, lease, or otherwise commercialize the Services without authorization</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Interfere with or disrupt the integrity or performance of the Services</Typography></li>
          </Box>
        </Box>

        {/* 5. User Accounts and Registration */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            5. User Accounts and Registration
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>5.1 Account Creation</Typography>
          <Typography variant="body1" sx={{ mb: 1, color: '#666', lineHeight: 1.8 }}>To use the Services, you must:</Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 3 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Create a User Account by providing accurate and complete information</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Be at least 18 years of age</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Have the legal capacity to enter into binding contracts</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Represent a legitimate business entity conducting lawful business in India</Typography></li>
          </Box>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>5.2 Account Security</Typography>
          <Typography variant="body1" sx={{ mb: 1, color: '#666', lineHeight: 1.8 }}>You are responsible for:</Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 2 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Maintaining the confidentiality of your account credentials</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>All activities that occur under your account</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Immediately notifying us of any unauthorized use or security breach</Typography></li>
          </Box>
        </Box>

        {/* 6. Subscription Plans and Fees */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            6. Subscription Plans and Fees
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>6.1 Subscription Fees</Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 3 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Payable in advance on a monthly or annual basis</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Denominated in Indian Rupees (INR)</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Exclude applicable taxes (GST, etc.) unless stated otherwise</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Non-refundable except as required by law</Typography></li>
          </Box>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>6.2 Payment Methods</Typography>
          <Typography variant="body1" sx={{ mb: 1, color: '#666', lineHeight: 1.8 }}>We accept:</Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 3 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Credit/debit cards</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Net banking</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>UPI</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Other payment methods through our payment processors (Razorpay, PayU, Cashfree)</Typography></li>
          </Box>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>6.3 Billing and Invoicing</Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 3 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>GST will be charged as per applicable rates and regulations</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>You must provide valid GSTIN for claiming input tax credit</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Payment is due within 7 days of invoice date</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>All payments must be made in Indian Rupees</Typography></li>
          </Box>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>6.4 Late Payment</Typography>
          <Typography variant="body1" sx={{ mb: 1, color: '#666', lineHeight: 1.8 }}>If payment is not received by the due date:</Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 3 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Interest at 2% per month may be charged on overdue amounts</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Your access to the Services may be suspended after 7 days of non-payment</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Your account may be terminated after 30 days of non-payment</Typography></li>
          </Box>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>6.5 Refund Policy</Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 2 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}><strong>Trial Period:</strong> We may offer a free trial period (7-14 days) for new users with no refund for unused trial periods</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}><strong>Monthly subscriptions:</strong> No refunds for partial months</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}><strong>Annual subscriptions:</strong> Refunds may be provided on a pro-rata basis within 30 days of purchase</Typography></li>
          </Box>
        </Box>

        {/* 7. Client Obligations and Responsibilities */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            7. Client Obligations and Responsibilities
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>7.1 Compliance with Laws</Typography>
          <Typography variant="body1" sx={{ mb: 1, color: '#666', lineHeight: 1.8 }}>You agree to:</Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 3 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Comply with all Applicable Laws in your use of the Services</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Comply with TRAI regulations, DND registries, and anti-spam laws</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Ensure compliance with Digital Personal Data Protection Act, 2023 (DPDPA)</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Maintain proper records as required by tax and regulatory authorities</Typography></li>
          </Box>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>7.2 Acceptable Use</Typography>
          <Typography variant="body1" sx={{ mb: 1, color: '#666', lineHeight: 1.8 }}>You agree to use the Services only for lawful business purposes. You will NOT:</Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 2 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Send spam, unsolicited messages, or engage in mass messaging without consent</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Violate TRAI's Do Not Disturb (DND) regulations</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Use the Services for fraudulent, deceptive, or misleading activities</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Collect or store personal data without proper consent and legal basis</Typography></li>
          </Box>
        </Box>

        {/* 8. Data Protection and Privacy */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            8. Data Protection and Privacy
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>8.1 Data Processing</Typography>
          <Typography variant="body1" sx={{ mb: 2, color: '#666', lineHeight: 1.8 }}>
            We act as a Data Processor for Client Data under DPDPA 2023. You act as the Data Fiduciary responsible for obtaining user consents. We implement appropriate technical and organizational security measures including:
          </Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 3 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Encryption in transit (SSL/TLS 256-bit) and at rest (AES-256)</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Role-based access controls and multi-factor authentication</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>24/7 security monitoring and incident response</Typography></li>
          </Box>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>8.2 Data Retention and Deletion</Typography>
          <Typography variant="body1" sx={{ mb: 1, color: '#666', lineHeight: 1.8 }}>After account termination:</Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 2 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>We retain Client Data for 30 days after account termination</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Data is permanently deleted after 30 days, except financial records retained for 7 years as required by Indian tax laws</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>You may request data export during the 30-day period</Typography></li>
          </Box>

          <Typography variant="body1" sx={{ mb: 2, color: '#666', lineHeight: 1.8 }}>
            Our Privacy Policy, available at <Link href="https://www.biznavigate.in/privacy-policy" color="primary">www.biznavigate.in/privacy-policy</Link>, is incorporated into these Terms by reference.
          </Typography>
        </Box>

        {/* 9. Intellectual Property Rights */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            9. Intellectual Property Rights
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>9.1 Our Intellectual Property</Typography>
          <Typography variant="body1" sx={{ mb: 1, color: '#666', lineHeight: 1.8 }}>
            BizNavigate and its licensors retain all right, title, and interest in and to:
          </Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 3 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>The Services, Platform, and all software, code, and technology</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>All trademarks, service marks, logos, and brand names</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>All documentation, materials, and content we provide</Typography></li>
          </Box>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>9.2 Your Intellectual Property</Typography>
          <Typography variant="body1" sx={{ mb: 2, color: '#666', lineHeight: 1.8 }}>
            You retain all right, title, and interest in and to your Client Data and your trademarks. By using the Services, you grant us a limited, non-exclusive, royalty-free license to process, store, and display Client Data as necessary to provide the Services.
          </Typography>
        </Box>

        {/* 10. Warranties and Disclaimers */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            10. Warranties and Disclaimers
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>10.1 Our Warranties</Typography>
          <Typography variant="body1" sx={{ mb: 3, color: '#666', lineHeight: 1.8 }}>
            We warrant that we will provide the Services with reasonable care and skill, and that the Services will substantially conform to the documentation.
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>10.2 DISCLAIMERS</Typography>
          <Box sx={{ bgcolor: '#fff3cd', p: 3, borderRadius: 2, mb: 2 }}>
            <Typography variant="body1" sx={{ mb: 2, color: '#333', lineHeight: 1.8, fontWeight: 600 }}>
              EXCEPT AS EXPRESSLY PROVIDED, THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND.
            </Typography>
            <Typography variant="body1" sx={{ mb: 1, color: '#333', lineHeight: 1.8 }}>
              WE DISCLAIM ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO:
            </Typography>
            <Box component="ul" sx={{ color: '#333', pl: 4, mb: 0 }}>
              <li><Typography variant="body1" sx={{ mb: 1 }}>IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT</Typography></li>
              <li><Typography variant="body1" sx={{ mb: 1 }}>WARRANTIES REGARDING AVAILABILITY, RELIABILITY, OR ACCURACY</Typography></li>
              <li><Typography variant="body1" sx={{ mb: 1 }}>WARRANTIES THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE</Typography></li>
            </Box>
          </Box>
        </Box>

        {/* 11. Limitation of Liability */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            11. Limitation of Liability
          </Typography>

          <Box sx={{ bgcolor: '#fff3cd', p: 3, borderRadius: 2, mb: 2 }}>
            <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>11.1 EXCLUSION OF CONSEQUENTIAL DAMAGES</Typography>
            <Typography variant="body1" sx={{ mb: 2, color: '#333', lineHeight: 1.8, fontWeight: 600 }}>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL BIZNAVIGATE BE LIABLE FOR ANY:
            </Typography>
            <Box component="ul" sx={{ color: '#333', pl: 4, mb: 2 }}>
              <li><Typography variant="body1" sx={{ mb: 1 }}>INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES</Typography></li>
              <li><Typography variant="body1" sx={{ mb: 1 }}>LOST PROFITS, REVENUE, SALES, OR BUSINESS</Typography></li>
              <li><Typography variant="body1" sx={{ mb: 1 }}>LOSS OF DATA OR BUSINESS INTERRUPTION</Typography></li>
            </Box>

            <Typography variant="h6" sx={{ mb: 1, mt: 2, fontWeight: 600, color: '#222' }}>11.2 LIABILITY CAP</Typography>
            <Typography variant="body1" sx={{ mb: 0, color: '#333', lineHeight: 1.8, fontWeight: 600 }}>
              OUR TOTAL AGGREGATE LIABILITY SHALL NOT EXCEED THE AMOUNTS PAID BY YOU TO US IN THE 12 MONTHS PRECEDING THE EVENT GIVING RISE TO LIABILITY, OR INR 10,000 (TEN THOUSAND RUPEES), WHICHEVER IS GREATER.
            </Typography>
          </Box>
        </Box>

        {/* 12. Indemnification */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            12. Indemnification
          </Typography>
          <Typography variant="body1" sx={{ mb: 1, color: '#666', lineHeight: 1.8 }}>
            You agree to indemnify, defend, and hold harmless BizNavigate from and against all claims, liabilities, damages, losses, costs, and expenses arising out of or related to:
          </Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 2 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Your use or misuse of the Services</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Your violation of these Terms</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Your violation of any Applicable Law or third-party rights</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Your violation of TRAI DND regulations or anti-spam laws</Typography></li>
          </Box>
        </Box>

        {/* 13. Term and Termination */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            13. Term and Termination
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>13.1 Termination by You</Typography>
          <Typography variant="body1" sx={{ mb: 3, color: '#666', lineHeight: 1.8 }}>
            You may cancel your subscription at any time through your account settings. Cancellation takes effect at the end of your current Subscription Period. No refunds for the current billing cycle.
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>13.2 Termination by Us</Typography>
          <Typography variant="body1" sx={{ mb: 1, color: '#666', lineHeight: 1.8 }}>We may immediately suspend or terminate your access if:</Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 3 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Your account is 30 days or more past due</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>We reasonably believe you are violating these Terms or Applicable Law</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>You engage in fraudulent, abusive, or illegal activities</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>You violate TRAI regulations or Third-Party Service policies</Typography></li>
          </Box>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>13.3 Effect of Termination</Typography>
          <Typography variant="body1" sx={{ mb: 1, color: '#666', lineHeight: 1.8 }}>Upon termination:</Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 2 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Your license to use the Services terminates immediately</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>You have 30 days to export your Client Data</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>All outstanding fees become immediately due and payable</Typography></li>
          </Box>
        </Box>

        {/* 14. Dispute Resolution */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            14. Dispute Resolution
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>14.1 Governing Law</Typography>
          <Typography variant="body1" sx={{ mb: 3, color: '#666', lineHeight: 1.8 }}>
            This Agreement shall be governed by and construed in accordance with the laws of India.
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>14.2 Jurisdiction</Typography>
          <Typography variant="body1" sx={{ mb: 3, color: '#666', lineHeight: 1.8 }}>
            The courts of Malappuram, Kerala, India shall have exclusive jurisdiction over any disputes arising out of or related to this Agreement.
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>14.3 Arbitration</Typography>
          <Typography variant="body1" sx={{ mb: 1, color: '#666', lineHeight: 1.8 }}>
            Any dispute that cannot be resolved through good faith negotiations shall be resolved by binding arbitration under the Arbitration and Conciliation Act, 1996:
          </Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 3 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Single arbitrator mutually agreed upon by the parties</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Seat of arbitration: Malappuram, Kerala, India</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>Language: English</Typography></li>
          </Box>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>14.4 Class Action Waiver</Typography>
          <Typography variant="body1" sx={{ mb: 2, color: '#666', lineHeight: 1.8, fontWeight: 600 }}>
            YOU AND BIZNAVIGATE AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING.
          </Typography>
        </Box>

        {/* 15. Compliance and Regulatory */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            15. Compliance and Regulatory
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>15.1 TRAI Regulations</Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 3 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>You will comply with TRAI's DND (Do Not Disturb) regulations</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>You will not send promotional messages to DND-registered numbers</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>You are solely responsible for TRAI compliance violations</Typography></li>
          </Box>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>15.2 GST Compliance</Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 3 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>You will provide valid GSTIN for tax purposes</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>You are responsible for applicable GST filings</Typography></li>
          </Box>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>15.3 Data Protection</Typography>
          <Box component="ul" sx={{ color: '#666', pl: 4, mb: 2 }}>
            <li><Typography variant="body1" sx={{ mb: 1 }}>You will comply with DPDPA 2023</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>You will obtain proper consents for data collection</Typography></li>
            <li><Typography variant="body1" sx={{ mb: 1 }}>You will honor data subject rights requests</Typography></li>
          </Box>
        </Box>

        {/* 16. General Provisions */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            16. General Provisions
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>16.1 Entire Agreement</Typography>
          <Typography variant="body1" sx={{ mb: 3, color: '#666', lineHeight: 1.8 }}>
            This Agreement, together with the Privacy Policy, constitutes the entire agreement between you and BizNavigate regarding the Services.
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>16.2 Amendments</Typography>
          <Typography variant="body1" sx={{ mb: 3, color: '#666', lineHeight: 1.8 }}>
            We may modify these Terms at any time. We will provide at least 30 days' notice for material changes. Continued use after the effective date constitutes acceptance.
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>16.3 Severability</Typography>
          <Typography variant="body1" sx={{ mb: 3, color: '#666', lineHeight: 1.8 }}>
            If any provision is found invalid, the provision will be modified to the minimum extent necessary or severed, and the remaining provisions will remain in full force.
          </Typography>

          <Typography variant="h6" sx={{ mb: 1, fontWeight: 600, color: '#222' }}>16.4 Force Majeure</Typography>
          <Typography variant="body1" sx={{ mb: 2, color: '#666', lineHeight: 1.8 }}>
            Neither party shall be liable for failure or delay due to causes beyond its reasonable control, including acts of God, war, terrorism, government actions, cyber attacks, or failures of Third-Party Services.
          </Typography>
        </Box>

        {/* 17. Contact Information */}
        <Box sx={{ mb: 5 }}>
          <Typography variant="h4" sx={{ mb: 2, fontWeight: 600, color: '#222', fontSize: { xs: '1.25rem', md: '1.5rem' } }}>
            17. Contact Information
          </Typography>
          <Typography variant="body1" sx={{ mb: 2, color: '#666', lineHeight: 1.8 }}>
            For questions, concerns, or notices regarding these Terms:
          </Typography>

          <Box sx={{ bgcolor: '#f5f5f5', p: 3, borderRadius: 2, mb: 2 }}>
            <Typography variant="body1" sx={{ mb: 1, color: '#666' }}><strong>General Inquiries:</strong></Typography>
            <Typography variant="body1" sx={{ mb: 1, color: '#666' }}>Email: <Link href="mailto:support@biznavigate.in" color="primary">support@biznavigate.in</Link></Typography>
            <Typography variant="body1" sx={{ mb: 2, color: '#666' }}>Phone: +91-8075624909</Typography>

            <Typography variant="body1" sx={{ mb: 1, color: '#666' }}><strong>Legal Notices:</strong></Typography>
            <Typography variant="body1" sx={{ mb: 2, color: '#666' }}>Email: <Link href="mailto:legal@biznavigate.in" color="primary">legal@biznavigate.in</Link></Typography>

            <Typography variant="body1" sx={{ mb: 1, color: '#666' }}><strong>Data Protection:</strong></Typography>
            <Typography variant="body1" sx={{ mb: 2, color: '#666' }}>Email: <Link href="mailto:privacy@biznavigate.in" color="primary">privacy@biznavigate.in</Link></Typography>

            <Typography variant="body1" sx={{ mb: 1, color: '#666' }}><strong>Security Issues:</strong></Typography>
            <Typography variant="body1" sx={{ mb: 2, color: '#666' }}>Email: <Link href="mailto:security@biznavigate.in" color="primary">security@biznavigate.in</Link></Typography>

            <Typography variant="body1" sx={{ mb: 1, color: '#666' }}><strong>Abuse Reports:</strong></Typography>
            <Typography variant="body1" sx={{ mb: 2, color: '#666' }}>Email: <Link href="mailto:abuse@biznavigate.in" color="primary">abuse@biznavigate.in</Link></Typography>

            <Typography variant="body1" sx={{ mb: 1, color: '#666' }}><strong>Registered Office:</strong></Typography>
            <Typography variant="body1" sx={{ mb: 1, color: '#666' }}>BIZNAVIGATE TECHNOLOGIES PRIVATE LIMITED</Typography>
            <Typography variant="body1" sx={{ mb: 1, color: '#666' }}>C/O ERAMU P V, PALLIKKAL</Typography>
            <Typography variant="body1" sx={{ mb: 1, color: '#666' }}>VALIYAPUTHOOR HOUSE</Typography>
            <Typography variant="body1" sx={{ mb: 1, color: '#666' }}>TIRURANGADI, PUTHUR-PALLIKKAL</Typography>
            <Typography variant="body1" sx={{ mb: 2, color: '#666' }}>MALAPPURAM - 673636</Typography>
            <Typography variant="body1" sx={{ mb: 2, color: '#666' }}>KERALA, INDIA</Typography>

            <Typography variant="body1" sx={{ mb: 0, color: '#666' }}><strong>Business Hours:</strong> Monday to Saturday: 10:00 AM - 7:00 PM IST</Typography>
          </Box>
        </Box>

        {/* Acceptance */}
        <Box sx={{ bgcolor: '#f0f7ff', p: 4, borderRadius: 2, mb: 5 }}>
          <Typography variant="h5" sx={{ mb: 2, fontWeight: 600, color: '#222', textAlign: 'center' }}>
            Acceptance
          </Typography>
          <Typography variant="body1" sx={{ mb: 2, color: '#333', lineHeight: 1.8, fontWeight: 600, textAlign: 'center' }}>
            BY CLICKING "I ACCEPT," CREATING AN ACCOUNT, OR USING THE SERVICES, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS OF SERVICE.
          </Typography>
          <Typography variant="body1" sx={{ mb: 0, color: '#333', lineHeight: 1.8, fontWeight: 600, textAlign: 'center' }}>
            IF YOU DO NOT AGREE TO THESE TERMS, DO NOT USE THE SERVICES.
          </Typography>
        </Box>

        <Box sx={{ mt: 6, pt: 4, borderTop: '1px solid #eee' }}>
          <Box sx={{ textAlign: 'center', color: '#666', fontSize: '0.875rem' }}>
            <Typography variant="body2" sx={{ display: 'block', mb: 0.5 }}><strong>Last Reviewed:</strong> December 10, 2025</Typography>
            <Typography variant="body2" sx={{ display: 'block', mb: 0.5 }}><strong>Version:</strong> 1.0</Typography>
            <Typography variant="body2" sx={{ display: 'block', mt: 2, fontStyle: 'italic' }}>
              Designed to comply with Indian laws including the Information Technology Act, 2000, Digital Personal Data Protection Act, 2023, and Consumer Protection Act, 2019
            </Typography>
          </Box>
        </Box>
      </Container>
    </Box>
  );
};

export default TermsOfService;
